## Workflow's name
#name: release kosmosctl for linux&darwin
#
## Workflow's trigger
#on:
#  push:
#    tags:
#      - "v*.*.*"

on:
  release:
    types:
      - published

# Workflow's jobs
jobs:
  # job's id
  release:
    # job's name
    name: release kosmosctl for linux&darwin

    # the type of machine to run the job on
    runs-on: ubuntu-20.04

    # create a build matrix for jobs
    strategy:
      fail-fast: false
      matrix:
        os: [linux, darwin]
        arch: [amd64, arm64]

    # create steps
    steps:
      # step1: check out repository
      - name: Check out git repository
        uses: actions/checkout@v3

      # step2: install go env
      - name: Install Go
        uses: actions/setup-go@v3

      # step3: make binaries
      - name: Make binaries
        run: make release

      # step4: create release
      - name: release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            _output/release/kosmosctl-${{ matrix.os }}-${{ matrix.arch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}